language: java
jdk:
  - openjdk7
branches:
  only:
    - master
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HPA05MU5caipG0V4HuQFpUXMQBLtv7ZVKYnTGsXL37HXM29UECcyLLxhQzQmJimb/3oqt02wyC19QydeJATByhs/td9Gw6pUiuFTHVzr+raQcVhwGr9uuvkVHTEisOBLo85X70BE3pOr8ssrCTrjKxT++S4r5f9vHLlzR3gUJGw="

addons:
  coverity_scan:
    project:
      name: "SaumilP/design-patterns"
      description: "Build submitted via Travis CI"
    notification_email: saumilpatel1@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
script:
  mvn compile test