language: java
jdk:
  - openjdk8

branches:
  only:
    - master

env:
  global:
   - secure: "P0m+VCrbrVn3ivv3JHg8beXHtOp140vwPXnscAXmk7VpqmsV80FjR3LdcnpGvghAAm8kGmHPro9NCjOe2IbQBvK+ILk21NmZn42gyOZtcTE7u0+Ftx1T5f0VoOOYgKLzuStSVkmHmiS9in7HYpLXKlgiEzvUwk2g2eP41rJeEKA="

addons:
  coverity_scan:
    project:
      name: "SaumilP/design-patterns"
      description: "Build submitted via Travis CI"
    notification_email: saumilpatel1@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

install:
  mvn package

script:
  mvn compile test

